### ISSUE TITLE
label_encoder bug

### ISSUE THREAD

**Issue by oserikov** [tchewik/isanlp_rst#1]
https://github.com/tchewik/isanlp_rst/blob/e845f0a2d7b6109c48bfe7af820a56823cc0761e/src/isanlp_rst/sklearn_classifier.py#L27-L29
кажется, в строке 29 нужно заменить `file_one_hot_encoder` на `file_label_encoder`. Открою PR?

**Comment by oserikov** [comment]
переоформил текст issue, а то случайно открыл недописанную

**Comment by tchewik** [comment]
Да, конечно
