### ISSUE TITLE
Main stream

### ISSUE THREAD

**Issue by IINemo** [tchewik/isanlp_rst#2]
Current:
1. Update segmentation model for Russian to the one used in the Shared Task.
2. Prepare a document with an example of inconsistency in the tree annotation.

Future:
1. Create a pipeline for rst parsing of Russian language.
2. Create a docker container that can be utilized as a stand-alone service (text in => rst annotation out) together with other linguistic services from isanlp.
3. Fix annotation of trees in the rst corpus.
4. Train a new model for rst construction of a rst trees.
5. Create a evaluation scripts for the whole pipeline.

**Comment by tchewik** [comment]
> Current:
> [x] 2. Prepare a document with an example of inconsistency in the tree annotation.

> Future:
> [x] 1. Create a pipeline for rst parsing of Russian language.
> [x] 2. Create a docker container that can be utilized as a stand-alone service (text in => rst annotation out) together with other linguistic services from isanlp.

**Comment by tchewik** [comment]
Current:
[x] 1. Update segmentation model for Russian to the one used in the Shared Task.

**Comment by IINemo** [comment]
Summarizing the updates

Done.
- <s>Update segmentation model for Russian to the one used in the Shared Task.</s>
- <s>Prepare a document with an example of inconsistency in the tree annotation.</s>
- <s> Create pipeline for rst parsing in Russian </s>

Current:
- Update model for tree construction
- Update model for nuclearity detection
- Implement NN model for relation classification: hierarchical GRU

Future:
- Create a docker container that can be utilized as a stand-alone service (text in => rst annotation out) together with other linguistic services from isanlp.
- Fix annotation of trees in the rst corpus.
- Create NN model for tree construction.
- Create a README for discourse parser.

**Comment by tchewik** [comment]
> Summarizing the updates
> 
> Done.
> 
> * Update segmentation model for Russian to the one used in the Shared Task.
> * Prepare a document with an example of inconsistency in the tree annotation.
> * Create pipeline for rst parsing in Russian
> * Create a docker container that can be utilized as a stand-alone service (text in => rst annotation out) together with other linguistic services from isanlp.
> 
> Current:
> 
> * Update model for tree construction
> * Update model for nuclearity detection
> * Implement NN model for relation classification: hierarchical GRU
> 
> Future:
> 
> * Fix annotation of trees in the rst corpus.
> * Create NN model for tree construction.
> * Create a README for discourse parser.

**Comment by tchewik** [comment]
> Summarizing the updates
>
> Done.
> - Update segmentation model for Russian to the one used in the Shared Task.
> - Prepare a document with an example of inconsistency in the tree annotation.
> - Create pipeline for rst parsing in Russian
> - Update model for tree construction
> - Update model for nuclearity detection
> - Implement NN model for relation classification: hierarchical GRU
> - Create a docker container that can be utilized as a stand-alone service (text in => rst annotation out) together with other linguistic services from isanlp.
> - Create NN model for tree construction.
> - Create a README for discourse parser.
>
> Future:
> - Fix annotation of trees in the rst corpus.

**Comment by IINemo** [comment]
Done.
- Added context
- Added related work

ToDo
- Collect the list of annotation mistakes (structure/ segmentation)
- Continue working on related work (survey of papers for the last 2-3 years)
- Consider revising the list of discourse relations for the parser

I will read the current paper template.
