### ISSUE TITLE
Неправильные позиции в тексте

### ISSUE THREAD

**Issue by Disassem** [tchewik/isanlp_rst#6]
В результатах работы RST-парсера версии 3.0 возвращаемые позиции (start, end) не соответствуют оригинальному тексту (т.е. часть текста, взятая из поданного на вход текста по позициям start и end, отличается от части текста, получаемого из поля text).
В версии 2.1 такой проблемы не было.

**Comment by tchewik** [comment]
В версии 3.0 сперва выполняется токенизация текста. Обращайтесь к токенизированному тексту, выдаваемому парсером.
